#pragma once
// -------------------------------------------------------------
//  CinematicSeqDB -- list of level-sequence (camera cutscene) master assets that exist in the game.
//  Loaded from res/cinematics/data.json (auto-updated from the repository at startup, like the
//  kamui / fbs dictionaries; generated by data/cinematics/generate_data.py from an asset dump).
//  Primary source for a sequence's season folder (polaris / polaris01 / ...) and for whether a
//  sequence exists at all. Entries: paths relative to /Game/cinematics without extension, e.g.
//    game/polaris02/aml/throw/02/aml_throw_02_cam1p_master
// -------------------------------------------------------------
#include <string>
#include <unordered_map>

class CinematicSeqDB
{
public:
    static CinematicSeqDB& Get();

    // Load (or reload) from data.json. Safe to call multiple times.
    void Load(const std::string& dataJsonPath);

    bool IsLoaded() const { return m_loaded; }
    size_t Count() const { return m_seasonByKey.size(); }

    // Season folder of an existing sequence, "" if no such asset.
    //   base: "game" / "demo"    tail: "<code>/<cat>/<sub>/<file>" (path below the season folder)
    std::string FindSeason(const std::string& base, const std::string& tail) const;

private:
    CinematicSeqDB() = default;

    std::unordered_map<std::string, std::string> m_seasonByKey; // "base/tail" -> season folder
    bool m_loaded = false;
};
